---
title: "Comparing frog 2C and gastrulation data"
author: "Edward Cruz"
date: "2026-02-19"
output: github_document
---


```{r Libraries }

rm(list=ls(all=T))
library(dplyr)
library(tidyr)
library(ggplot2)
library(patchwork)

knitr::opts_chunk$set(fig.path = "figures/Comp_Frog_Early-MBT/")

```


```{r Data for time course length }

Frog_T5_all.min <- c(161, 221, 281, 401, 521, 641,
                     881, 1605, 1961, 2918, 4405) - 161
Frog_T6_all.min <- c(150, 210, 270, 390, 510, 635,
                     930, 1591, 1950, 2910, 4394) - 150
Frog_Early.min <- c(Frog_T5_all.min + Frog_T6_all.min)/2

Frog_MBT.min <- c(1472, 1502, 1535, 1592, 1714, 1832,
                  2412, 2934, 3270, 3749, 4260, 4411) - 1472

colorblind_palette <- c("#CC79A7", "#D55E00", "#0072B2", "#F0E442",
                        "#009E73", "#56B4E9", "#E69F00", "#999999")

```


```{r Importing theoretical peptide data }

early_theo_peps <- read.csv("Files/Fits/XLA_O18-Early-TS_Theo-Peptide-Decay.csv")
mbt_theo_peps <-read.csv("Files/Fits/XLA_O18-MBT-TS_Theo-Peptide-Decay.csv")

```


```{r Shared theoretical peptides }

shared_theo_peps <- merge(early_theo_peps, mbt_theo_peps, by="Peptide",
                          suffixes=c("_2C", "_MBT"))

head(shared_theo_peps)

```


```{r Comparing 2C and gastrulation residue probabilties }

median_2cell_residues <- read.csv("Files/Fits/AA_examples/Median_2cell_residue-prob.csv")
median_gast_residues <- read.csv("Files/Fits/AA_examples/Median_Gast_residue-prob.csv")


ex.p <- ggplot() +
  geom_point(data=median_2cell_residues, 
             aes(x=Time, y=Fit_values), color="#0072B2", size=2,
             shape=1) +
  geom_point(data=median_gast_residues, 
             aes(x=Time, y=Fit_values), color="#CC79A7", size=2,
             shape=1) +

  # # geom_line(data=ex.fit_data[ex.fit_data$Type=="2C_Min",],
  # #           aes(x=Time, y=Fit_values), color="#0072B2", size=1.5,
  # #           alpha=0.25, linetype="dashed") +
  # geom_line(data=ex.fit_data[ex.fit_data$Type=="2C_Median",],
  #           aes(x=Time, y=Fit_values), color="#0072B2", size=1.5) +  
  # 
  # # geom_line(data=ex.fit_data[ex.fit_data$Type=="MBT_Min",],
  # #           aes(x=Time, y=Fit_values), color="#CC79A7", size=1.5,
  # #           alpha=0.25, linetype="dashed") +
  # geom_line(data=ex.fit_data[ex.fit_data$Type=="MBT_Median",],
  #           aes(x=Time, y=Fit_values), color="#CC79A7", size=1.5) +  
  theme_bw() +
  labs(x="Hours after Labeling", y="Prob. of light peptide") +
  theme_bw() +
  theme(axis.text=element_text(size=21,colour="black"),
        plot.title = element_text(size=24, hjust=0.5),
        axis.title = element_text(size=22),
        panel.border = element_rect(linewidth=2),
        panel.grid.major = element_line(color = "grey70", linewidth = 0.25),
        panel.grid.minor = element_line(color = "grey70", linewidth = 0.25),
        aspect.ratio = 1,
        legend.position = "none") +
  coord_cartesian(ylim=c(0,1), xlim=c(0,6))


# #Uncomment for new image!
# tiff("graph.tiff", units="in",
#      width=4, height=4, res=300)

ex.p

# dev.off() #Uncomment for new image!

```


```{r Median decay times for 2C and gastrulation }

median_2cell_residues[median_2cell_residues$Fit_values<0.5,][1,]
median_gast_residues[median_gast_residues$Fit_values<0.5,][1,]

```



```{r Importing and merging fitted dataframes }

early_fits.df <- read.csv("Files/Fits/Dyn-Model/XLA_O18_T5-6_FinalFits_ALL.csv")
mbt_fits.df <- read.csv("Files/Fits/Dyn-Model/XLA_O18_T9-10_FinalFits_ALL.csv")

length(unique(c(early_fits.df$Protein_ID, mbt_fits.df$Protein_ID)))

early_fits.df <- early_fits.df[early_fits.df$Estimate=="interval",]
mbt_fits.df <- mbt_fits.df[mbt_fits.df$Estimate=="interval",]

early_min_kd <- log(2)/(4244*3)
early_max_hl <- log(2)/early_min_kd/60

mbt_min_kd <- log(2)/(2939*3)
mbt_max_hl <- log(2)/mbt_min_kd/60

combined_ts <- merge(early_fits.df[c("Protein_ID", "Human_Gene", "kD",
                                     "T5_kD", "T6_kD",
                                     "HL_Hrs", "mClass", "Number_Pep_Fits")],
                     mbt_fits.df[c("Protein_ID", "kD",
                                   "T9_kD", "T10_kD",                                   
                                   "HL_Hrs", "mClass", "Number_Pep_Fits")],
                     by="Protein_ID", suffixes=c("_Early", "_MBT"))

combined_ts[(combined_ts$mClass_Early=="Deg") &
              (combined_ts$kD_Early < early_min_kd), "mClass_Early"] <- "Deg-Long"
combined_ts[(combined_ts$mClass_MBT=="Deg") &
              (combined_ts$kD_MBT < mbt_min_kd), "mClass_MBT"] <- "Deg-Long"

combined_ts["Comb_kD"] <- (combined_ts$kD_Early + combined_ts$kD_MBT)/2
combined_ts["Combined_Class"] <- paste0(combined_ts$mClass_Early, "_", combined_ts$mClass_MBT)
# combined_ts <- combined_ts[!combined_ts$Comb_kD==1e-6,]

combined_ts <- combined_ts %>%
  arrange(desc(kD_Early))

```


```{r Biplot of kDs between experiments }

ss_bp.all <- combined_ts
ss_bp.all <- ss_bp.all[ss_bp.all$mClass_Early=="Deg" | ss_bp.all$mClass_Early=="Deg-Long" |
                         ss_bp.all$mClass_MBT=="Deg" | ss_bp.all$mClass_MBT=="Deg-Long",]

ss_bp.all["Log10_Early"] <- abs(ss_bp.all$kD_Early)
ss_bp.all["Log10_Late"] <- abs(ss_bp.all$kD_MBT)
ss_bp.all["Log10_Early"] <- log10(ss_bp.all$Log10_Early)
ss_bp.all["Log10_Late"] <- log10(ss_bp.all$Log10_Late)
ss_bp.all[ss_bp.all$Log10_Early<(-6), "Log10_Early"] <- (-6)
ss_bp.all[ss_bp.all$Log10_Late<(-6), "Log10_Late"] <- (-6)


p1 <- ggplot() +
  geom_point(data=ss_bp.all[ss_bp.all$Human_Gene %in%
                              c("CCNB1", "KIF22", "GMNN"),],
             aes(x=Log10_Late, y=Log10_Early),
             size=3, stroke=1,
             color="#56B4E9") +

  geom_point(data=ss_bp.all[ss_bp.all$Human_Gene %in%
                              c("CDT1", "CDC6"),],
             aes(x=Log10_Late, y=Log10_Early),
             size=3, stroke=1,
             color="#CC79A7") +

  geom_point(data=ss_bp.all[ss_bp.all$Human_Gene %in%
                              c("TDRKH"),],
             aes(x=Log10_Late, y=Log10_Early),
             size=3, stroke=1,
             color="#F0E442") +
  geom_point(data=ss_bp.all[ss_bp.all$Human_Gene %in%
                              c("GMNN", "CCNB1", "KIF22",
                                "CDT1", "CDC6", "TDRKH"),],
             aes(x=Log10_Late, y=Log10_Early),
             size=3, stroke=1, shape=1,
             color="black") +
    
  geom_point(data=ss_bp.all,
             aes(x=Log10_Late, y=Log10_Early),
             shape=1, size=3, stroke=1, alpha=0.25,
             color="black") +
  geom_hline(yintercept=log10(early_min_kd), linetype="dashed") +
  geom_vline(xintercept=log10(mbt_min_kd), linetype="dashed") +  

  geom_abline(slope=1, intercept=0, color="black", linetype="dotted",
              linewidth=1) +
  labs(x=expression("Gastrulation log"[10]*"(min"^-1*")"),
       y=expression("2-cell log"[10]*"(min"^-1*")")) +
  theme_bw() +
  theme(axis.text=element_text(size=22,colour="black"),
        plot.title = element_text(size=24, hjust=0.5),
        axis.title = element_text(size=20),
        axis.line.x.bottom = element_line(color = "black", linewidth = 1),
        axis.line.y.left   = element_line(color = "black", linewidth = 1),       
        # panel.border = element_rect(linewidth=1.5),
        panel.border = element_blank(),        
        panel.grid.major = element_line(color = "grey90", linewidth = 0.25),
        panel.grid.minor = element_line(color = "grey90", linewidth = 0.25),
        aspect.ratio = 1,
        legend.position = "none",
        plot.margin = margin(t = 10, r = 25, b = 10,
                             l = 10, unit = "pt")) +
  coord_cartesian(xlim = c(-6,-1),
                  ylim = c(-6,-1))

# #Uncomment for new image!
# tiff("graph.tiff", units="in",
#      width=5, height=5, res=300)

p1

# dev.off() #Uncomment for new image!

```


```{r Setting times again }

Frog_T5_all.min <- c(161, 221, 281, 401, 521, 641,
                     881, 1605, 1961, 2918, 4405)
Frog_T5_light.min <- Frog_T5_all.min[c(1:2, 4:5, 7:8, 10:11)]

Frog_T6_all.min <- c(150, 210, 270, 390, 510, 635,
                     930, 1591, 1950, 2910, 4394)
Frog_T6_light.min <- Frog_T6_all.min[c(1:2, 4:5, 7:8, 10:11)]

#--------------------------------

early_heavy_time <- (Frog_T5_all.min + Frog_T6_all.min)/2
early_light_time <- (Frog_T5_light.min + Frog_T6_light.min)/2

mbt_heavy_time <- c(1472, 1502, 1535, 1592, 1714, 1832,
                    2412, 2934, 3270, 3749, 4260, 4411)
mbt_light_time <- mbt_heavy_time[c(1,3,5,7,9,11:12)]

```


```{r Example proteins }

plot_protein <- function(protein_id, title_color="black") {
  
  sub_early <- early_fits.df[early_fits.df$Protein_ID == protein_id,]
  sub_mbt <- mbt_fits.df[mbt_fits.df$Protein_ID == protein_id,]

  early_light <- as.numeric(sub_early[10:17])
  early_light <- early_light / early_light[1]
  
  early_label <- as.numeric(sub_early[18:28])
  early_label <- early_label / early_label[1]
      
  mbt_light <- as.numeric(sub_mbt[10:16])
  mbt_light <- mbt_light / mbt_light[1]  
  
  mbt_label <- as.numeric(sub_mbt[17:28])  
  mbt_label <- mbt_label / mbt_label[1]
    
  all_data <- data.frame(Time=c(early_light_time, early_heavy_time,
                                mbt_light_time, mbt_heavy_time),
                         Values=c(early_light, early_label,
                                  mbt_light, mbt_label),
                         Group=c(rep("2C_Light", length(early_light)),
                                 rep("2C_Label", length(early_label)),
                                 rep("Gast_Light", length(mbt_light)),
                                 rep("Gast_Label", length(mbt_label))))
  all_data$Time <- all_data$Time/60
  all_data <- all_data[!all_data$Group %in% c("2C_Light", "Gast_Light"),]
  
  
  p1 <- ggplot() +
    geom_line(data=all_data, aes(x=Time, y=Values, color=Group),
              size=2) +
    geom_hline(yintercept = 1, linetype="dashed", linewidth=1,
               color="black") +
    geom_vline(xintercept=early_heavy_time[1]/60,
               linetype="dotted", linewidth=1) +
    geom_vline(xintercept=mbt_heavy_time[1]/60,
               linetype="dotted", linewidth=1) + 
    annotate("text", x=30, y=1.15, label="2-cell", color="#A63D00",
             hjust=0, size=10) +
    annotate("text", x=50, y=1.15, label="Gast.", color="#E69F00",
             hjust=0, size=10) +
    
    annotate("text", x=45, y=0.7,
             label=paste(round(as.numeric(sub_early["HL_Hrs"]),1), "hrs"),
             color="#A63D00", hjust=0, size=10) +
    annotate("text", x=45, y=0.5,
             label=paste(round(as.numeric(sub_mbt["HL_Hrs"]),1), "hrs"),
             color="#E69F00", hjust=0, size=10) +
    # annotate("text", x=45, y=0.5,
    #          label="Stable",
    #          color="#E69F00", hjust=0, size=10) +
    
    labs(title=as.character(sub_early["Human_Gene"])) +
    theme_bw() +
    theme(axis.text=element_text(size=21,colour="black"),
          plot.title = element_text(size=26, hjust=0.5, color=title_color),
          # axis.title = element_text(size=20),
          axis.title = element_blank(),          
          panel.border = element_rect(linewidth=2),
          panel.grid.major = element_line(color = "grey90", linewidth = 0.25),
          panel.grid.minor = element_line(color = "grey90", linewidth = 0.25),
          legend.position = "none",
          plot.margin = margin(t = 10, r = 25, b = 10,
                               l = 10, unit = "pt")) +
    coord_cartesian(ylim=c(0,1.25)) +
    scale_color_manual(values=c("#A63D00", "#E69F00"))

  return(p1) }

# #Uncomment for new image!
# tiff("graph.tiff", units="in",
#      width=6, height=3.5, res=300)

plot_protein("XBmRNA10569|XBXL10_1g5638")
plot_protein("XBmRNA51997|XBXL10_1g27704")
plot_protein("XBmRNA79044|XBXL10_1g42043")
plot_protein("XBmRNA34319|XBXL10_1g18654")
plot_protein("XBmRNA79355|XBXL10_1g42215")
plot_protein("XBmRNA69786|XBXL10_1g37002")

# dev.off() #Uncomment for new image!

```


```{r Classifying shifts in determined groups }

combined_ts["Class_Shift"] <- combined_ts$Combined_Class
combined_ts[combined_ts$Class_Shift ==
              "Deg-Long_Deg-Long",
            "Class_Shift"] <- "Always Long"
combined_ts[combined_ts$Class_Shift ==
              "Deg-Long_Deg",
            "Class_Shift"] <- "Long to Deg"
combined_ts[combined_ts$Class_Shift ==
              "Deg-Long_Flat",
            "Class_Shift"] <- "Long to Stable"

combined_ts[combined_ts$Class_Shift ==
              "Deg_Deg",
            "Class_Shift"] <- "Always Deg"
combined_ts[combined_ts$Class_Shift ==
              "Deg_Deg-Long",
            "Class_Shift"] <- "Deg to Long"
combined_ts[combined_ts$Class_Shift ==
              "Deg_Flat",
            "Class_Shift"] <- "Deg to Stable"

combined_ts[combined_ts$Class_Shift ==
              "Flat_Flat",
            "Class_Shift"] <- "Always Stable"
combined_ts[combined_ts$Class_Shift ==
              "Flat_Deg-Long",
            "Class_Shift"] <- "Stable to Long"
combined_ts[combined_ts$Class_Shift ==
              "Flat_Deg",
            "Class_Shift"] <- "Stable to Deg"

table(combined_ts$Class_Shift)

```


```{r Example of how bar plots for supplemental figures were generated }

early_classes <- as.data.frame(table(combined_ts$mClass_MBT))
colnames(early_classes) <- c("Category", "Count")

early_classes$Category <- factor(early_classes$Category,
                                 levels=c("Deg", "Deg-Long", "Flat"))

early_classes$Count / sum(early_classes$Count) * 100

p1 <- ggplot(early_classes, aes(x = "", y = Count, fill = Category)) +
  geom_bar(stat = "identity", color="black", alpha=0.8) +
  labs(x = NULL,        # Removes the blank x-axis label
       # y = "Number of proteins",
       fill = "Class") +
  theme_bw() +
  theme(axis.text=element_text(size=16,colour="black"),
        plot.title = element_text(size=24, hjust=0.5),
        axis.title = element_blank(),
        axis.ticks.x = element_blank(),
        panel.border = element_rect(linewidth=1.5),
        panel.grid.major = element_line(color = "grey90", linewidth = 0.25),
        panel.grid.minor = element_line(color = "grey90", linewidth = 0.25),
        legend.position = "none",
        plot.margin = margin(t = 10, r = 25, b = 10,
                             l = 10, unit = "pt")) +
  scale_fill_manual(values=c("#5E4FA2", "#56B4E9", "#999999"))


# #Uncomment for new image!
# tiff("graph.tiff", units="in",
#      width=2, height=5, res=300)

p1

# dev.off() #Uncomment for new image!

```


```{r All classes }

table(combined_ts$Class_Shift)

```


```{r Example of how pie charts for supplemental figures were generated }

summary.data <- data.frame(
  category = c("Long", "Deg", "Stable"),
  count = c(265, 807, 590))

# summary.data <- data.frame(
#   category = c("Long", "Deg", "Stable"),
#   count = c(76, 3, 281))

# summary.data <- data.frame(
#   category = c("Long", "Deg", "Stable"),
#   count = c(112, 61, 4609))

x <- round(summary.data$count / sum(summary.data$count) * 100,1)
names(x) <- summary.data$category
x

summary.data["category"] <- factor(summary.data$category,
                                   levels=summary.data$category)

# Create a pie chart
deg.pie <- ggplot(summary.data, aes(x = 1, y = count, fill = category)) +
  geom_bar(width = 1, stat = "identity", color = "black", alpha=0.8) +
  coord_polar(theta = "y") +
  xlim(0.5, 1.5) +
  scale_fill_manual(values = c("#56B4E9", "#5E4FA2", "#767676")) +
  theme_void()

deg.pie

ggsave('test.png', bg="transparent", plot=deg.pie,width=4,height=4,units="in")

```


```{r Plotting HLs for each combined group }

plot_deg_hist <- function(group) {
  
  sub_data <- combined_ts[combined_ts$Class_Shift==group,]$HL_Hrs_Early
  print(median(sub_data))
  sub_data <- data.frame(x=sub_data)
  
  p1 <- ggplot(sub_data, aes(x = x)) +
    geom_histogram(aes(y = after_stat(density)), 
                   binwidth = 5,
                   fill = "grey70", 
                   color = "black", 
                   alpha = 0.7) +
    geom_density(color = "darkred", linewidth = 1.5) +
    geom_vline(xintercept = median(sub_data$x), linetype="dashed",
               linewidth=1) +
    labs(title = group,
         x = "2-cell half-life (Hours)",
         y = "Density") +
    theme_bw() +
    theme(axis.text=element_text(size=21,colour="black"),
          plot.title = element_text(size=22, hjust=0.5),
          axis.title = element_text(size=22),
          panel.border = element_rect(linewidth=2),
          panel.grid.major = element_line(color = "grey90", linewidth = 0.25),
          panel.grid.minor = element_line(color = "grey90", linewidth = 0.25),
          legend.position = "none",
          plot.margin = margin(t = 10, r = 25, b = 10,
                               l = 10, unit = "pt")) +
    coord_cartesian(ylim=c(0,0.015))
  
  return(p1) }


# #Uncomment for new image!
# tiff("graph.tiff", units="in",
#      width=7, height=3.5, res=300)

plot_deg_hist("Always Deg")
plot_deg_hist("Deg to Long")
plot_deg_hist("Deg to Stable")

# dev.off() #Uncomment for new image!

```


```{r Median of degrading to non degrading classes }

median(combined_ts[combined_ts$Class_Shift %in% c("Deg to Long", "Deg to Stable"),]$HL_Hrs_Early)

```


```{r}

sessionInfo()

```




