---
title: "Fly Turnover Analysis"
author: "Edward Cruz"
date: "2026-05-12"
output: github_document
---


```{r Libraries }

rm(list=ls(all=T))
library(lsa)
library(fgsea)
library(stats)
library(GO.db)
library(tidyr)
library(dplyr)
library(ggplot2)
library(stringr)
library(KEGGREST)
library(rrvgo)
library(org.Hs.eg.db)
library(clusterProfiler)
library(minpack.lm)
library(Biostrings)
library(Peptides)
library(ggpubr)
library(forcats)
library(patchwork)

knitr::opts_chunk$set(fig.path = "figures/fly_turnover_analysis/")

```


```{r Importing data from other scripts }

#Ultimately - collected these minutes apart so used one vector
Fly_T6.time.min <- c(257, 287, 320, 351, 386, 441, 500,
                     565, 682, 868, 995, 1218, 1514) - 257
light_time <- c(0, Fly_T6.time.min[c(4, 8, 11, 13)])

Fly_T6_hpf_time <- ((Fly_T6.time.min + 257) + (Fly_T6.time.min + 117))/2
Fly_T6_hpf_time <- Fly_T6_hpf_time / 60
Fly_T6_hpf_light_time <- c(Fly_T6_hpf_time[1], Fly_T6_hpf_time[c(4, 8, 11, 13)])

#------------------------------------------

fly_blast_fits <- 
  read.csv("Files/Fits/Dyn-Model/Fly_O18_T6-7_FinalFits_ALL.csv")

head(fly_blast_fits)

```


```{r Calculating gastrulation precision limits }

max_fit_kd <- log(2)/(tail(Fly_T6.time.min, 1)*3)
max_fit_hl <- log(2)/max_fit_kd/60
cat("Max Half-life (hrs):\t", max_fit_hl) 

```


```{r Mapping fly GO terms }

fly_GO_map <- read.csv("Systems/Fly_GO-Terms.csv")
fly_GO_map <- fly_GO_map[fly_GO_map$Protein_ID %in%
                           fly_blast_fits$Protein_ID,]
fly_GO_map <- apply(fly_GO_map, 1, function(x){

  BP_terms <- trimws(strsplit(x["GO_BP"], ";")[[1]])
  BP_id <- sub(".*\\[(GO:\\d+)\\].*", "\\1", BP_terms)
  BP_desc <- sub("\\s*\\[GO:.*\\]", "", BP_terms)

  MF_terms <- trimws(strsplit(x["GO_MF"], ";")[[1]])
  MF_id <- sub(".*\\[(GO:\\d+)\\].*", "\\1", MF_terms)
  MF_desc <- sub("\\s*\\[GO:.*\\]", "", MF_terms)

  CC_terms <- trimws(strsplit(x["GO_CC"], ";")[[1]])
  CC_id <- sub(".*\\[(GO:\\d+)\\].*", "\\1", CC_terms)
  CC_desc <- sub("\\s*\\[GO:.*\\]", "", CC_terms)

  out_df <- data.frame(Protein_ID=rep(x["Protein_ID"],
                                      length(c(BP_id, MF_id, CC_id))),
                       ID=c(BP_id, MF_id, CC_id),
                       Desc=c(BP_desc, MF_desc, CC_desc),
                       Type=c(rep("BP", length(BP_id)),
                              rep("MF", length(MF_id)),
                              rep("CC", length(CC_id))))

  return(out_df) }) %>% bind_rows

#This dataframe is solely to count terms and remove <10 annotations
fly_GO_counts <- data.frame(table(fly_GO_map$ID))
fly_GO_counts <- fly_GO_counts[fly_GO_counts$Freq > 20,]

#df of GO terms for identified and mapped proteins
fly_GO_annot <- unique(fly_GO_map[c("ID", "Type", "Desc")])
fly_GO_annot <- fly_GO_annot[fly_GO_annot$ID %in% fly_GO_counts$Var1,]
row.names(fly_GO_annot) <- NULL

head(fly_GO_annot)

```


```{r Setting rank order for GO-term enrichment }

enrich_kd <- fly_blast_fits[fly_blast_fits$Protein_ID %in% fly_GO_map$Protein_ID,
                            c("Protein_ID", "kD", "O12")]
enrich_kd <- enrich_kd %>% arrange(kD, desc(O12))

enrich_kd["Rank"] <- seq(1, nrow(enrich_kd))
enrich_kd["Signed_Rank"] <- enrich_kd$Rank - mean(enrich_kd$Rank)
enrich_kd["Signed_Rank"] <- enrich_kd$Signed_Rank / max(enrich_kd$Signed_Rank)
enrich_kd <- enrich_kd %>%
  select(Signed_Rank, Protein_ID, kD) %>%
  arrange(desc(Signed_Rank))

protein_stats <- setNames(enrich_kd$Signed_Rank, enrich_kd$Protein_ID)

head(protein_stats)
cat("\n\n")
tail(protein_stats)

```


```{r Filtering fly GO data }

filtered_fly_GO <- fly_GO_map
filtered_fly_GO <- filtered_fly_GO[filtered_fly_GO$ID %in% fly_GO_annot$ID,]

fly_GO_ref <- lapply(unique(filtered_fly_GO$ID),
       function(x){

         term <- fly_GO_map[fly_GO_map$ID == x,]$Protein_ID

         return(term) })

names(fly_GO_ref) <- unique(filtered_fly_GO$ID)

fly_GO_ref[1]

```


```{r Enrichment test }

# Run enrichment
set.seed(123)   # reproducible fgsea permutations
res <- fgseaMultilevel(
  pathways = fly_GO_ref,
  stats    = protein_stats,
  minSize  = 10,
  maxSize  = 500)

#Order your results by significance
res <- res[order(res$padj), ]

# fgsea's built-in collapsing function
# Compares the leading edge genes of nested pathways and drops redundant ones
collapsed_pathways <- collapsePathways(res, fly_GO_ref, protein_stats)

#Filter main results to keep only the 'parent' representative terms
res <- res[res$pathway %in% collapsed_pathways$mainPathways, ]
res <- res[res$padj < 0.05,] %>% as.data.frame
res <- merge(res, fly_GO_annot, by.x="pathway",  by.y="ID")
res <- res %>% arrange(desc(NES))
res <- res[c("pathway", "NES", "padj", "size", "Type", "Desc")]

head(res[c("NES", "Type", "Desc")])

```


```{r Selecting representative GO terms }

custom_GO_names <- c("GO:0051301", "GO:0006260", "GO:0004674", "GO:0000981",
                     "GO:0061630", "GO:0007155",
                     "GO:0006457", "GO:0006635", "GO:0005759", "GO:0000502",
                     "GO:0022626", "GO:0008017")
names(custom_GO_names) <- c("Cell division", "DNA replication", "Protein kinase activity",
                            "Transcription factor activity", "Ubiquitin protein ligase activity",
                            "Cell adhesion", "Protein folding", "Fatty acid β-oxidation",
                            "Mitochondrial matrix", "Proteasome complex", "Cytosolic ribosome",
                            "Microtubule binding")

custom_GO_names <- data.frame(GO=custom_GO_names,
                              Custom_Name=names(custom_GO_names))
custom_GO_terms <- merge(res, custom_GO_names,
                         by.x="pathway", by.y="GO") %>% arrange(desc(NES))
custom_GO_terms

```


```{r GO term plot }

p1 <- ggplot(custom_GO_terms, aes(x = NES, size = size,
                                  y = reorder(Custom_Name, NES))) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_point(alpha = 1) +
  geom_point(shape = 1, color = "black", stroke=0.8) +
  scale_y_discrete(labels = function(x) str_wrap(x, width = 50)) +  # wrap for display only
  scale_color_continuous(low = "grey80", high = "grey30", trans = "reverse") +
  labs(
    x = "Normalized enrichment score",
    y = "GO term",
    size = "Set size"
  ) +
  theme_bw() +
  theme(
    legend.text = element_text(size = 12, colour = "black"),
    legend.title = element_text(size = 12, colour = "black"),    
    axis.text = element_text(size = 13, colour = "black"),    
    plot.title = element_text(size = 18, hjust = 0.5),
    axis.title.x = element_text(size=16),
    axis.title.y = element_blank(),    
    panel.border = element_rect(linewidth = 1),
    plot.margin = margin(t = 5, r = 10, b = 15, l = 7, unit = "pt"),
    legend.position = c(0.25,0.75),
    legend.background = element_rect(colour = "black", linewidth = 0.5,
                                     fill = "white")
  ) +
  coord_cartesian(xlim=c(-4,3))

# #Uncomment for new image!
# tiff("graph.tiff", units="in",
#      width=6, height=4, res=300)

p1

# dev.off() #Uncomment for new image!

```


```{r Binning data for compartment analysis }

target_bins <- data.frame(
  Macro_Compartment = c("Nucleus", "Cytoplasm", "Mitochondrion", "Endoplasmic reticulum", 
                        "Plasma membrane", "Golgi apparatus", "Extracellular region", 
                        "Chromatin", "Vesicle"),
  Macro_GO_ID = c("GO:0005634", "GO:0005737", "GO:0005739", "GO:0005783", 
                  "GO:0005886", "GO:0005794", "GO:0005576", 
                  "GO:0000785", "GO:0031982"))

#---------------------------

offspring_map <- as.list(GOCCOFFSPRING[target_bins$Macro_GO_ID])

mapping_df <- lapply(names(offspring_map),
                               function(parent_id) {
  data.frame(Macro_GO_ID = parent_id,
             Specific_GO_ID = offspring_map[[parent_id]],
             stringsAsFactors = FALSE) }) %>% bind_rows

mapping_df <- rbind(data.frame(Macro_GO_ID = target_bins$Macro_GO_ID,
                               Specific_GO_ID = target_bins$Macro_GO_ID),
                    mapping_df)

mapping_df <- merge(mapping_df, target_bins, by="Macro_GO_ID")
head(mapping_df)

```


```{r Reoganizing data for compartment analysis }

fly_macro_CC <- fly_blast_fits[c("Protein_ID", "Gene_Symbol",
                                 "kD", "HL_Hrs", "mClass")]
# fly_macro_CC <- fly_macro_CC[!fly_macro_CC$mClass=="Noise // Weak Evidence",]
# fly_macro_CC[!fly_macro_CC$mClass=="Quantifiable degradation",
#              "HL_Hrs"] <- max_fit_hl

fly_macro_CC <- merge(fly_macro_CC,
                      unique(fly_GO_map[c("Protein_ID", "ID")]),
                      by="Protein_ID")
fly_macro_CC <- fly_macro_CC[fly_macro_CC$ID %in%
                               mapping_df$Specific_GO_ID,]

fly_macro_CC <- merge(fly_macro_CC, mapping_df[2:3],
                      by.x="ID", by.y="Specific_GO_ID")
fly_macro_CC["ID"] <- NULL
fly_macro_CC <- unique(fly_macro_CC) %>% arrange(Protein_ID)

CC_prot_counts <- data.frame(table(fly_macro_CC$Protein_ID))
fly_macro_CC <- fly_macro_CC[fly_macro_CC$Protein_ID %in%
                               CC_prot_counts[CC_prot_counts$Freq<=2,]$Var1,]

all_prot_CC <- unique(fly_macro_CC[-7])
all_prot_CC["Macro_Compartment"] <- "All proteins"

fly_macro_CC <- rbind(fly_macro_CC, all_prot_CC)
fly_macro_CC["log_kD"] <- log10(abs(fly_macro_CC$kD))

```


```{r Ordering compartment data }

CC_ordering <- lapply(unique(fly_macro_CC$Macro_Compartment),
       function(x){
         
         sub_df <- fly_macro_CC[fly_macro_CC$Macro_Compartment == x,]
         
         max_hl_rows <- nrow(sub_df[sub_df$HL_Hrs == max_fit_hl,])

         percent_collapsed <- max_hl_rows/nrow(sub_df)
         median_hl <- median(sub_df$HL_Hrs)
          
         out_line <- data.frame(CC=x, HL=median_hl,
                                Collapse_Percent = round(percent_collapsed*100,0),
                                Deg_Percent = 100-round(percent_collapsed*100,0))

         return(out_line) }) %>% bind_rows %>%
  arrange(CC != "All proteins", -HL, -Collapse_Percent)

fly_macro_CC$Macro_Compartment <- factor(fly_macro_CC$Macro_Compartment,
                                         levels=CC_ordering$CC)

head(CC_ordering)

```


```{r Bottom of Compartment plot }

p_kd_CC <- ggplot(data=fly_macro_CC,
                  aes(x = Macro_Compartment, y = HL_Hrs)) +

  geom_boxplot(fill="#5E4FA2", alpha=0.7,
               outliers=FALSE, width = 0.7, color = "black") +
  
  geom_vline(xintercept = 1.5, linetype="dashed",
             color = "black", linewidth = 1) +

  stat_summary(fun = median, geom = "point", 
               shape = 21, size = 3, fill = "red3", color = "black") +

  # geom_text(data = CC_ordering,
  #           aes(x = CC, y = max_fit_hl, label = paste0(Deg_Percent, "%")),
  #           vjust = -0.6, size = 5, inherit.aes = FALSE) +
    
  theme_bw() +
  labs(x = "Cellular Compartment",
       y = "Half-life (hours)") +
  
  theme(axis.text.x = element_text(angle = 35, size=15, hjust = 1, colour="black"),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size=16,colour="black"),
        axis.title.y = element_text(size=16, hjust=0.2),        
        plot.title = element_blank(),
        panel.border = element_rect(linewidth=1.2),
        panel.grid.major = element_line(color = "grey90", linewidth = 0.25),
        panel.grid.minor = element_line(color = "grey90", linewidth = 0.25),
        plot.margin = margin(t = 10, r = 25, b = 10,
                             l = 10, unit = "pt")) +
  coord_cartesian(ylim = c(0,65)) +
  scale_y_continuous(breaks=seq(0,60,20))
  
p_kd_CC

```


```{r Complete compartment plot }

prop_df <- CC_ordering %>%
  pivot_longer(cols = -c(CC, HL),
               names_to = "Type",
               values_to = "Percent")
prop_df$CC <- factor(prop_df$CC, levels=CC_ordering$CC)

# --- top track: 100% stacked proportion bar ---
p_bar <- ggplot(prop_df, aes(x = CC, y = Percent, fill = Type)) +
  geom_col(width = 0.7, colour = "black", alpha=0.7) +
  geom_vline(xintercept = 1.5, linetype = "dashed", colour = "black", linewidth = 1) +
  scale_fill_manual(values = c(Deg_Percent = "#5E4FA2",
                               Collapse_Percent = "#767676"),
                    labels = c("No measurable degradation", "Degrading")) +
  labs(y = "% of prot.") +
  theme_bw() +
  theme(axis.text.x  = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y  = element_text(size = 16, colour = "black"),
        axis.title.y = element_text(size = 16),
        panel.border = element_rect(linewidth = 1.2),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        legend.text = element_text(size = 16),
        legend.title = element_blank(),
        plot.margin = margin(t = 15, r = 25,
                             b = 0, l = 0, unit = "pt")) +
  scale_y_continuous(breaks = c(0,50,100), expand = expansion(mult = c(0, 0)))

# --- bottom: your existing boxplot, x-title/labels live here ---
p_box <- p_kd_CC + theme(plot.margin = margin(t = 0, r = 25, b = 0, l = 10, unit = "pt"))

# --- stack, aligned x-axis ---
p_combined <- p_bar / p_box + plot_layout(heights = c(1, 4.3))

# #Uncomment for new image!
# tiff("graph.tiff", units="in",
#      width=8, height=5, res=300)

p_combined

# dev.off() #Uncomment for new image!

```


```{r Importing interproscan data }

fly_deg_proteins <- fly_blast_fits$Protein_ID

interproscan_fly <- 
  read.csv("Systems/Fly_Interproscan/Dmel_Uniprot_Proteome_Interproscan.csv")

interproscan_fly <- interproscan_fly[interproscan_fly$Protein_ID %in%
                                       fly_deg_proteins,]
interproscan_fly <- unique(interproscan_fly[c("Protein_ID", "Signature_Accession",
                                              "Signature_Description")])

sub_IP_fly <- data.frame(table(interproscan_fly$Signature_Accession)) %>%
  arrange(Freq)
sub_IP_fly <- sub_IP_fly[sub_IP_fly$Freq>=4,]$Var1
sub_IP_fly <- sapply(sub_IP_fly, as.character)

length(sub_IP_fly)
sub_IP_fly[1:10]

```


```{r Combining deg rates with domain data }

domain_sub <- fly_blast_fits[c("Protein_ID", "Gene_Symbol", "kD", "HL_Hrs", "mClass")]
domain_sub <- merge(domain_sub,
                    interproscan_fly[c("Protein_ID", "Signature_Accession",
                                       "Signature_Description")],
                    by="Protein_ID") %>% arrange(HL_Hrs)
# domain_sub <-  domain_sub[domain_sub$Signature_Accession %in%
#                             sub_IP_fly,] %>% arrange(desc(Avg_kD))

head(domain_sub)

```


```{r Selecting PFAM domains of interest }

pfam_domains <- c("PF00225", "PF01437", "PF00096", "PF00595", "PF00567",
                  "PF02984", "PF00028", "PF00176", "PF02207", "PF00439",
                  "PF13445", "PF00632", "PF00069", "PF07525", "PF00046", 
                  "PF00022", "PF00472", "PF00191", "PF01399", "PF00012",
                  "PF00227", "PF00118", "PF00106", "PF00023")

names(pfam_domains) <-
  c("Kinesin motor", "Plexin repeat", "Znf-C2H2", "PDZ", "Tudor",
    "Cyclin-Cterm", "Cadherin", "SNF2-related", "UBR box", "Bromo",
    "RING-Znf", "HECT", "Protein kinase", "SOCS box", "Homeo",
    "Actin", "RF-1", "Annexin", "PCI", "Hsp70",
    "Proteasome subunit", "TCP1-cnp60 chaperonin", "Short chain dehydrogenase",
    "Ankyrin repeat")

```


```{r Reorganizing domain data for plotting }

domain_all_data <- lapply(pfam_domains, function(pfam){

  sub_df <- domain_sub[domain_sub$Signature_Accession == pfam,]

  sub_df[sub_df$kD<0, "HL_Hrs"] <- max_fit_hl
  sub_df[sub_df$kD<max_fit_kd, "HL_Hrs"] <- max_fit_hl
  sub_df$Signature_Description <- rep(names(pfam_domains[pfam_domains==pfam]),
                                      nrow(sub_df))

  return(sub_df)}) %>% bind_rows

domain_all_data <- domain_all_data[domain_all_data$Signature_Accession %in% sub_IP_fly,]

domain_all_data <- domain_all_data[!domain_all_data$Signature_Description %in%
    c("Actin", "RF-1", "Annexin", "Hsp70", "Proteasome subunit",
      "TCP1-cnp60 chaperonin", "Short chain dehydrogenase"),]

head(domain_all_data)

```


```{r Median half life of PCI domain }

median(fly_blast_fits[fly_blast_fits$Protein_ID %in% domain_all_data[domain_all_data$Signature_Accession == "PF01399",]$Protein_ID,]$HL_Hrs)

```


```{r Domain plot }

deg_domains <- ggplot(domain_all_data, aes(x = reorder(Signature_Description, -HL_Hrs,
                                                       FUN = median),
                                           y = HL_Hrs)) +

  # geom_hline(yintercept = max_fit_hl, linetype = "dashed",
  #            color = "black", linewidth=1) +
  geom_boxplot(outliers = FALSE, fill = "grey90", color = "black", alpha = 0.7,
               linewidth=0.8) +
  stat_summary(fun = median, geom = "point", 
               shape = 21, size = 3, fill = "red3", color = "black") +
  labs(title = "Protein Half-Lives by InterPro Domain",
       x = "Protein domain", y = "Half-life (hours)") +
  theme_bw() +
  theme(axis.text.x = element_text(size = 24,colour="black",
                                   angle=35, hjust=1),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size=28,colour="black"),
        axis.title.y = element_text(size=28),
        plot.title = element_blank(),
        panel.border = element_rect(linewidth=2),
        panel.grid.major = element_line(color = "grey90", linewidth = 0.25),
        panel.grid.minor = element_line(color = "grey90", linewidth = 0.25),
        legend.position = "none",
        plot.margin = margin(t = 10, r = 25, b = 10,
                             l = 10, unit = "pt"))

# #Uncomment for new image!
# tiff("graph.tiff", units="in",
#      width=16, height=5.5, res=300)

deg_domains

# dev.off() #Uncomment for new image!


```


```{r Importing IUPred data for disorder analysis }

fly_iupred <- read.csv("Systems/iupred2a/Dmel_Uniprot_IUPred2A-results.csv")
fly_iupred$Protein_ID <- sapply(strsplit(fly_iupred$Protein_ID,
                                         split = "\\|"),
                                "[", 2)

fly_idr_res <- fly_blast_fits[c("Protein_ID", "Gene_Symbol",
                                "kD", "HL_Hrs", "mClass")]
fly_idr_res <- merge(fly_idr_res, fly_iupred, by="Protein_ID") %>%
  arrange(desc(kD))

fly_idr_res["IDR_Class"] <- "N/A"
fly_idr_res[fly_idr_res$Mean_IUPred>=0.5,"IDR_Class"] <- "Disordered"
fly_idr_res[fly_idr_res$Mean_IUPred<0.5,"IDR_Class"] <- "Ordered"

# --- Are disordered proteins more likely to be degrading AT ALL? ------------
fly_idr_res$IDR_Class <- factor(fly_idr_res$IDR_Class,
                                levels = c("Ordered", "Disordered"))

prop_tab <- table(IDR_Class = fly_idr_res$IDR_Class,
                  Degrading = fly_idr_res$mClass)

# chi-square (Fisher is needlessly slow at this n; result is identical in spirit)
prop_test <- chisq.test(prop_tab)

print(prop_test)
cat("\n\n\n")

# --- AMONG degraders, do disordered ones degrade faster? ------------

deg <- fly_idr_res %>% filter(mClass=="Deg") 

rate_test <- t.test(log10(kD) ~ IDR_Class, data = deg)
print(rate_test)

```


```{r Disorder domain plotting for bottom }

IDR_boxplot_df <- cbind(fly_idr_res[c("IDR_Class", "HL_Hrs")],
                        data.frame(Set=rep("All", nrow(fly_idr_res))))
IDR_boxplot_df <- rbind(IDR_boxplot_df,
                        cbind(deg[c("IDR_Class", "HL_Hrs")],
                              data.frame(Set=rep("Degrading", nrow(deg)))))

p1 <- ggplot(IDR_boxplot_df,
             aes(x = IDR_Class, y = HL_Hrs, fill = Set,
                 group=interaction(IDR_Class, Set))) +
  geom_boxplot(width = 0.5, color = "black",
               outliers = FALSE, alpha=0.7,
               position=position_dodge(width = 0.6)) +
  stat_summary(fun = median, geom = "point",
               shape = 21, size = 3, fill = "red3", color = "black",
               position = position_dodge(width = 0.6)) +
  scale_fill_manual(values = c(All = "#D55E00", Degrading = "#5E4FA2")) +
  theme_bw() +
  theme(axis.text.y = element_text(size=16, colour="black"),
        axis.text.x = element_text(size = 15, colour="black"),
        axis.title.y = element_text(size=18),
        axis.title.x = element_blank(),
        plot.title = element_blank(),
        panel.border = element_rect(linewidth=1.2),
        panel.grid.major = element_line(color = "grey90", linewidth = 0.25),
        panel.grid.minor = element_line(color = "grey90", linewidth = 0.25),
        legend.position = "none",
        plot.margin = margin(t = 0, r = 25, b = 0, l = 10, unit = "pt")) +
  labs(y=expression("Half-life (hours)")) +
  coord_cartesian(ylim=c(0,60)) +
  scale_y_continuous(breaks=c(0, 10, 30, 50))

```


```{r Final disorder plot }

dist_idr_df <- 
  rbind(data.frame(table(fly_idr_res[fly_idr_res$IDR_Class=="Ordered",]$mClass)),
        data.frame(table(fly_idr_res[fly_idr_res$IDR_Class=="Disordered",]$mClass)))
dist_idr_df["IDR"] <- c("Ordered", "Ordered", "Disordered", "Disordered")
dist_idr_df[1:2, "Freq"] <- dist_idr_df$Freq[1:2] / 4872
dist_idr_df[3:4, "Freq"] <- dist_idr_df$Freq[3:4] / 993
dist_idr_df$IDR <- factor(dist_idr_df$IDR, levels=c("Ordered", "Disordered"))
dist_idr_df$Var1 <- factor(dist_idr_df$Var1, levels=c("Flat", "Deg"))

p2 <- ggplot(dist_idr_df, aes(x = IDR, y = Freq*100, fill = Var1)) +
  geom_col(width = 0.6, colour = "black", alpha=0.7) +
  scale_fill_manual(values = c(Deg = "#5E4FA2",
                               Flat = "#767676"),
                    labels = c("No measurable degradation", "Degrading")) +
  labs(y = "% of prot.") +
  theme_bw() +
  theme(axis.text.x  = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y  = element_text(size = 16, colour = "black"),
        axis.title.y = element_text(size = 18),
        panel.border = element_rect(linewidth = 1.2),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        legend.text = element_text(size = 14),
        legend.title = element_blank(),
        plot.margin = margin(t = 0, r = 25,
                             b = 0, l = 0, unit = "pt")) +
  scale_y_continuous(breaks = c(0,50,100), expand = expansion(mult = c(0, 0)))


# --- stack, aligned x-axis ---
p_combined <- p2 / p1 + plot_layout(heights = c(1, 2.5))

# #Uncomment for new image!
# tiff("graph.tiff", units="in",
#      width=3.7, height=3.5, res=300)

p_combined

# dev.off() #Uncomment for new image!

```


```{r Determining grouped class for each protein }

all_tracks_df <- fly_blast_fits
all_tracks_df["Light_FC"] <- apply(all_tracks_df, 1, function(row){
  
  light_fc <- as.numeric(row["N16"]) / as.numeric(row["T0_L"])
  
  return(light_fc) })

inc_min_fc <- 1.439371 
dec_min_fc <- 0.6218052 

all_tracks_df["Light_Type"] <- rep("Unchanging", nrow(all_tracks_df))
all_tracks_df[all_tracks_df$Light_FC > inc_min_fc, "Light_Type"] <- "Increasing"
all_tracks_df[all_tracks_df$Light_FC < dec_min_fc, "Light_Type"] <- "Decreasing"

all_tracks_df["Merged_Class"] <- paste0(all_tracks_df$Light_Type, "_", all_tracks_df$mClass)

table(all_tracks_df$Merged_Class)

```


```{r Pie chart of kinetic classes }

summary.data <- data.frame(
  category = c("No measurable degradation", "Balanced Protein Turnover",
               "Protein Degradation Only", "Net Protein Increase with Degradation",
               "Protein Synthesis Only"),
  count = c(279+44, 3477, 724, 1157, 186))

sum(summary.data$count)
summary.data$category
cat("\n")
round(summary.data$count / sum(summary.data$count) * 100,1)

summary.data["category"] <- factor(summary.data$category,
                                   levels=c("No measurable degradation",
                                            "Protein Synthesis Only",
                                            "Net Protein Increase with Degradation",
                                            "Balanced Protein Turnover",
                                            "Protein Degradation Only"))

# Create a pie chart
deg.pie <- ggplot(summary.data, aes(x = 1, y = count, fill = category)) +
  geom_bar(width = 1, stat = "identity", color = "black", alpha=0.8,
           linewidth=0.25) +
  coord_polar(theta = "y") +
  xlim(0.5, 1.5) +
  scale_fill_manual(values = c("grey100", "grey80", "grey55", "grey20", "black")) +
  theme_void()

deg.pie

ggsave('test.png', bg="transparent", plot=deg.pie,width=4,height=4,units="in")

```


```{r Example proteins }

plot_protein <- function(protein_id){

  protein_sub <- fly_blast_fits[fly_blast_fits$Protein_ID==protein_id,]  

  print(protein_sub$Gene_Symbol)
  
  light_data <- as.numeric(protein_sub[9:13])
  light_data <- light_data / light_data[1]
  
  heavy_data <- as.numeric(protein_sub[14:26])
  heavy_data <- heavy_data / heavy_data[1]

  plot_data <- data.frame(Time=c(Fly_T6_hpf_light_time,
                                 Fly_T6_hpf_time),
                          Values=c(light_data, heavy_data),
                          Group=c(rep("Control",
                                      length(Fly_T6_hpf_light_time)),
                                  rep("O18",
                                      length(Fly_T6_hpf_time))))  

  p1 <- ggplot() +
    geom_line(data=plot_data[plot_data$Group=="O18",],
              aes(x=Time, y=Values, group=Group),
              color="#36A893", size=3) +
    geom_line(data=plot_data[plot_data$Group=="Control",],
              aes(x=Time, y=Values, group=Group),
              color="#767676", size=3) +    
    theme_bw() +
    theme(axis.text=element_text(size=18,colour="black"),
          plot.title = element_text(size=22, hjust=0.5),
          axis.title = element_blank(),
          panel.border = element_rect(linewidth=2),
          panel.grid.major = element_line(color = "grey90", linewidth = 0.25),
          panel.grid.minor = element_line(color = "grey90", linewidth = 0.25),
          legend.position = "none",
          aspect.ratio = 1,
          plot.margin = margin(t = 5, r = 5, b = 5,
                               l = 5, unit = "pt")) +    
    geom_hline(yintercept = 1, linetype="dashed", linewidth=1) +
    coord_cartesian(ylim=c(0,3))
  
  return(p1) }

# #Uncomment for new image!
# tiff("graph.tiff", units="in",
#      width=10, height=5, res=300)

plot_protein("Q94529") |
plot_protein("Q9VEK7") |
plot_protein("Q9W2E9") |
plot_protein("A0A4D6K881") |
plot_protein("Q9VUI0")

# i <- 1
# i <- i + 1
# print(i)
# all_tracks_df[all_tracks_df$Merged_Class == "Decreasing_Deg","Gene_Symbol"][i]
# 
# plot_protein(all_tracks_df[all_tracks_df$Merged_Class == "Decreasing_Deg","Protein_ID"][i])

# dev.off() #Uncomment for new image!

```


```{r}

sessionInfo()

```
















