---
title: "Frog AA Incorporation"
author: "Edward Cruz"
date: "2025-04-25"
output: github_document
---

```{r Libraries }

rm(list=ls(all=T))
library(tidyr)
library(dplyr)
library(splines)
library(stringr)
library(ggplot2)
library(patchwork)
library(data.table)
library(minpack.lm)
library(parallel)

num_cores <- detectCores() - 1  # Save one core for system stability
knitr::opts_chunk$set(fig.path = "figures/Frog_AA_Incorporation_MBT-T2/")

```


```{r Reference table for amino acids }

aa.profiles <- read.csv("Files/Reference/AA_Profiles.csv")

head(aa.profiles)

```


```{r Time for labeling period }

#Time in minutes of timepoints collected, spline time is coarser
#Note: These are the exact timepoint matches for proteomics samples
AA_T2.time <- c(0, 30, 60, 120, 180, 300, 485,
                725, 1440, 1800, 2886)

```


```{r Importing MN metabolomics data }

merged_frog_table <- read.csv("Data/XLA_AAA/XLA_O18-T1-T2_results-merge_AA.csv")
merged_frog_table <- merged_frog_table[!grepl("blank", merged_frog_table$Sample),]

early_exp_id <- "col009b"
mbt_exp_id <- "col009b2"

MBT_AA_table <- merged_frog_table[grepl(paste(mbt_exp_id, "_", sep=""),
                                        merged_frog_table$Sample),]

cat("Missing AAs: ", 
    aa.profiles$Name[!aa.profiles$Name %in% unique(MBT_AA_table$compound)],
    "\n")

```


```{r Removing noisy timepoints }

#Removing inaccurate timepoint
AA_T2.time <- c(0, 30, 60, 120, 180, 300, 485,
                725, 1440, 2886)

MBT_AA_table <- MBT_AA_table[!MBT_AA_table$Sample == "col009b2_T9",]

```



```{r Generating matrix in correct format for analysis }

#'*Looping through unique amino acids and reformatting table*
MBT_AA_matrix <- sapply(unique(MBT_AA_table$compound), function(x){
  aa.data <- MBT_AA_table[MBT_AA_table$compound==x,] #selecting AA

  aa_wide <- aa.data %>% #Reformating columns long-wise
    pivot_wider(
      id_cols = c(compound, Sample),
      names_from = isotopeLabel,
      values_from = fraction.all ) %>%
    arrange(compound, Sample)  

  #Binding total number of O18-labels
  aa_wide <- cbind(data.frame(Total=rep(sum(grepl("O18", colnames(aa_wide))),
                                        nrow(aa_wide))),
                   aa_wide)
    
  return(aa_wide) })

MBT_AA_matrix <- bind_rows(MBT_AA_matrix)

#'*Calculating median values for missing AAs*
MBT_med_values <- lapply(paste("T", c(seq(0,8,1),10), sep=""), function(time){
  #Calculating median for timepoints collected
  t_data <- MBT_AA_matrix[MBT_AA_matrix$Sample == paste("col009b2_", time, sep=""),]

    
  sub_2 <- t_data[t_data$compound %in% c("arginine", "cysteine",
                                         "glycine", "valine", "histidine",
                                         "isoleucine", "leucine", "lysine",
                                         "methionine", "phenylalanine",
                                         "proline", "tryptophan"),]
  med_2 <- apply(sub_2[c("C12 PARENT", "O18-label-1",
                         "O18-label-2")], 2, median)
  med_2 <- med_2 / sum(med_2) #Necessary to remake row sum = 1

  
  sub_3 <- t_data[t_data$compound %in% c("glutamine"),]  
  med_3 <- apply(sub_3[c("C12 PARENT", "O18-label-1",
                         "O18-label-2", "O18-label-3")], 2, median)
  med_3 <- med_3 / sum(med_3) #Necessary to remake row sum = 1

    
  sub_4 <- t_data[t_data$compound %in% c("glutamate", "aspartate"),]
  med_4 <- apply(sub_4[c("C12 PARENT", "O18-label-1",
                         "O18-label-2", "O18-label-3",
                         "O18-label-4")], 2, median)
  med_4 <- med_4 / sum(med_4) #Necessary to remake row sum = 1
  

  row_out <- data.frame(Name=rep("median", 3),
                        AA=c("X", "U", "Z"),
                        Total=c(2,3,4),
                        Sample=paste("col009b2_", time, sep=""))
  
  return(cbind(row_out, bind_rows(med_2, med_3, med_4))) })

#Merging and appending to table of all amino acids
MBT_med_values <- do.call(rbind, MBT_med_values)
MBT_AA_matrix <- merge(aa.profiles[c("Name", "AA")],
                       MBT_AA_matrix, by.x="Name",
                       by.y="compound")

MBT_AA_matrix <- bind_rows(MBT_AA_matrix, MBT_med_values)
MBT_AA_matrix$Name <- sub("^(\\w)", "\\U\\1", MBT_AA_matrix$Name, perl = TRUE)

head(MBT_AA_matrix)
 
```


```{r Exporting matrix for other scripts }

write.csv(MBT_AA_matrix, "Data/XLA_O18/Isotopic_Envelopes/Frog_MBT_AA_Matrix.csv",
          row.names = FALSE)

```


```{r Setting groups of AA by # of Oxygens }

#Frog Essential AAs
measured_AAs <- unique(MBT_AA_matrix$AA)

no_Oxy_AA <- c("A", "R", "C", "G", "V",
               "H", "I", "L", "K",
               "M", "F", "P", "W",
               "T", "Y", "X") 
no_Oxy_AA <- no_Oxy_AA[no_Oxy_AA %in% setdiff(measured_AAs, c("A"))]

one_Oxy_AA <- c("Q", "S", "N", "U") 
one_Oxy_AA <- one_Oxy_AA[one_Oxy_AA %in% setdiff(measured_AAs, c("N"))]

two_Oxy_AA <- c("D", "E", "Z")
two_Oxy_AA <- two_Oxy_AA[two_Oxy_AA %in% measured_AAs]

```


```{r Fitting splines for no Oxygen AAs }

no_Oxy.splines <- do.call(rbind, lapply(no_Oxy_AA, function(AA) {

  # Example setup
  interpolated_times <- seq(0, 2886, by = 1)
  sub.data <- MBT_AA_matrix[MBT_AA_matrix$AA == AA,]

  sub.data["time"] <- gsub("col009b2_T", "", sub.data$Sample)  
    
  sub.data["Sample"] <- gsub("col009b2_T", "", sub.data$Sample) %>% as.numeric
  sub.data <- sub.data %>% arrange(Sample)

  if (AA=="Y") { knot_positions <- c(50, 200) }   
  else if (AA %in% c("M")) { knot_positions <- c(20, 200) }     
  else if (AA %in% c("P", "H")) { knot_positions <- c(50, 500) }     
  else if (AA %in% c("A")) { knot_positions <- c(50, 00) }       
  else { knot_positions <- c(120, 300)   }
  

  # Fit spline models
  c12_fit <- lm(`C12 PARENT` ~ bs(AA_T2.time, degree = 3,
                                  knots = knot_positions), data = sub.data)
  o18_1_fit <- lm(`O18-label-1` ~ bs(AA_T2.time, degree = 3,
                                     knots = knot_positions), data = sub.data)
  o18_2_fit <- lm(`O18-label-2` ~ bs(AA_T2.time, degree = 3,
                                     knots = knot_positions), data = sub.data)

  # Predict spline values
  c12_pred <- predict(c12_fit, newdata = data.frame(AA_T2.time = interpolated_times))
  o18_1_pred <- predict(o18_1_fit, newdata = data.frame(AA_T2.time = interpolated_times))
  o18_2_pred <- predict(o18_2_fit, newdata = data.frame(AA_T2.time = interpolated_times))

  # Combine into one dataframe for ggplot
  spline_df <- data.frame(AA=rep(AA, length(interpolated_times)),
                          Labels=rep(2, length(interpolated_times)),
                          Time=rep(interpolated_times, 3),
                          Type=c(rep("C12", length(interpolated_times)),
                                 rep("O18_1", length(interpolated_times)),
                                 rep("O18_2", length(interpolated_times))),
                          Value=c(c12_pred, o18_1_pred, o18_2_pred))
  spline_df["AA"] <- AA
  spline_df[spline_df$Value > 1, "Value"] <- 1
  spline_df[spline_df$Value < 0, "Value"] <- 0

  # x <- ggplot() +
  #   geom_point(data=data.frame(x=AA_T2.time,
  #                              y=sub.data$`C12 PARENT`),
  #              aes(x=x,y=y), size=3) +
  #   geom_line(data=spline_df[spline_df$Type=="C12",],
  #              aes(x=Time,y=Value), size=1) +
  #   theme_bw() +
  #   coord_cartesian(ylim=c(0,1))
  # print(x)
  # invokeRestart("abort")
      
  return(spline_df)
    
}))

```


```{r  Fitting splines for one Oxygen AAs }

one_Oxy.splines <- do.call(rbind, lapply(one_Oxy_AA,
                                         function(AA) {

  # Example setup
  interpolated_times <- seq(0, 2886, by = 1)
  sub.data <- MBT_AA_matrix[MBT_AA_matrix$AA == AA,]
  sub.data["Sample"] <- gsub("col009b2_T", "", sub.data$Sample) %>% as.numeric
  sub.data <- sub.data %>% arrange(Sample)


  if (AA=="U") { knot_positions <- c(120,500) }
  
  else if (AA=="S") { knot_positions <- c(60,300) }
  else { knot_positions <- c(180,500) }
    
  # Fit spline models
  c12_fit <- lm(`C12 PARENT` ~ bs(AA_T2.time, degree = 3,
                                  knots = knot_positions), data = sub.data)
  o18_1_fit <- lm(`O18-label-1` ~ bs(AA_T2.time, degree = 3,
                                     knots = knot_positions), data = sub.data)
  o18_2_fit <- lm(`O18-label-2` ~ bs(AA_T2.time, degree = 3,
                                     knots = knot_positions), data = sub.data)
  o18_3_fit <- lm(`O18-label-3` ~ bs(AA_T2.time, degree = 3,
                                     knots = knot_positions), data = sub.data)
  
  # Predict spline values
  c12_pred <- predict(c12_fit, newdata = data.frame(AA_T2.time = interpolated_times))
  o18_1_pred <- predict(o18_1_fit, newdata = data.frame(AA_T2.time = interpolated_times))
  o18_2_pred <- predict(o18_2_fit, newdata = data.frame(AA_T2.time = interpolated_times))
  o18_3_pred <- predict(o18_3_fit, newdata = data.frame(AA_T2.time = interpolated_times))

  # Combine into one dataframe for ggplot
  spline_df <- data.frame(AA=rep(AA, length(interpolated_times)),
                          Labels=rep(3, length(interpolated_times)),
                          Time=rep(interpolated_times, 4),
                          Type=c(rep("C12", length(interpolated_times)),
                                 rep("O18_1", length(interpolated_times)),
                                 rep("O18_2", length(interpolated_times)),
                                 rep("O18_3", length(interpolated_times))),
                          Value=c(c12_pred, o18_1_pred, o18_2_pred, o18_3_pred))
  spline_df["AA"] <- AA
  spline_df[spline_df$Value > 1, "Value"] <- 1
  spline_df[spline_df$Value < 0, "Value"] <- 0

  # x <- ggplot() +
  #   geom_point(data=data.frame(x=AA_T2.time,
  #                              y=sub.data$`C12 PARENT`),
  #              aes(x=x,y=y), size=3) +
  #   geom_line(data=spline_df[spline_df$Type=="C12",],
  #              aes(x=Time,y=Value), size=1) +
  #   theme_bw() +
  #   coord_cartesian(ylim=c(0,1))
  # print(x)
  
  return(spline_df)

}))

```


```{r  Fitting splines for two Oxygen AAs }

two_Oxy.splines <- do.call(rbind, lapply(two_Oxy_AA,
                                         function(AA) {

  # Example setup
  interpolated_times <- seq(0, 2886, by = 1)
  sub.data <- MBT_AA_matrix[MBT_AA_matrix$AA == AA,]
  sub.data["Sample"] <- gsub("col009b2_T", "", sub.data$Sample) %>% as.numeric
  sub.data <- sub.data %>% arrange(Sample)

  knot_positions <- c(120,200)    

  # Fit spline models
  c12_fit <- lm(`C12 PARENT` ~ bs(AA_T2.time, degree = 3,
                                  knots = knot_positions), data = sub.data)
  o18_1_fit <- lm(`O18-label-1` ~ bs(AA_T2.time, degree = 3,
                                     knots = knot_positions), data = sub.data)
  o18_2_fit <- lm(`O18-label-2` ~ bs(AA_T2.time, degree = 3,
                                     knots = knot_positions), data = sub.data)
  o18_3_fit <- lm(`O18-label-3` ~ bs(AA_T2.time, degree = 3,
                                     knots = knot_positions), data = sub.data)
  o18_4_fit <- lm(`O18-label-4` ~ bs(AA_T2.time, degree = 3,
                                     knots = knot_positions), data = sub.data)
    
  # Predict spline values
  c12_pred <- predict(c12_fit, newdata = data.frame(AA_T2.time = interpolated_times))
  o18_1_pred <- predict(o18_1_fit, newdata = data.frame(AA_T2.time = interpolated_times))
  o18_2_pred <- predict(o18_2_fit, newdata = data.frame(AA_T2.time = interpolated_times))
  o18_3_pred <- predict(o18_3_fit, newdata = data.frame(AA_T2.time = interpolated_times))
  o18_4_pred <- predict(o18_4_fit, newdata = data.frame(AA_T2.time = interpolated_times))
  
  # Combine into one dataframe for ggplot
  spline_df <- data.frame(AA=rep(AA, length(interpolated_times)*5),
                          Labels=rep(4, length(interpolated_times)*5),
                          Time=rep(interpolated_times, 5),
                          Type=c(rep("C12", length(interpolated_times)),
                                 rep("O18_1", length(interpolated_times)),
                                 rep("O18_2", length(interpolated_times)),
                                 rep("O18_3", length(interpolated_times)),
                                 rep("O18_4", length(interpolated_times))),
                          Value=c(c12_pred, o18_1_pred, o18_2_pred, o18_3_pred,
                                  o18_4_pred))
  spline_df["AA"] <- AA
  spline_df[spline_df$Value > 1, "Value"] <- 1
  spline_df[spline_df$Value < 0, "Value"] <- 0

  # x <- ggplot() +
  #   geom_point(data=data.frame(x=AA_T2.time,
  #                              y=sub.data$`C12 PARENT`),
  #              aes(x=x,y=y), size=3) +
  #   geom_line(data=spline_df[spline_df$Type=="C12",],
  #              aes(x=Time,y=Value), size=1) +
  #   theme_bw() +
  #   coord_cartesian(ylim=c(0,1))
  # print(x)
  
  return(spline_df)
    
}))

```


```{r Final merged table of AAs and their splines }

all_splines.merge <- rbind(no_Oxy.splines, one_Oxy.splines, two_Oxy.splines)
all_splines.merge <- do.call(rbind,
              lapply(unique(all_splines.merge$AA), function(AA) {

  #Looping through each time to verify rowsum=1 for each AA
  c_df <- lapply(seq(0, 2886, by = 1), function(t) {
    sub_t <- all_splines.merge[all_splines.merge$AA==AA &
                              all_splines.merge$Time==t,]
    sub_t["Value"] <- sub_t$Value / sum(sub_t$Value)
    
    return(sub_t) })
  
  c_df <- do.call(rbind, c_df)

  return(c_df) }))

head(all_splines.merge)

```


```{r Plot of metabolomics data and corresponding splines }

all_spline.p <- lapply(no_Oxy_AA, function(ind_AA){
  
  sub.data <- MBT_AA_matrix[MBT_AA_matrix$AA == ind_AA,]
  sub.data["Sample"] <- gsub("col009b2_T", "", sub.data$Sample) %>% 
    as.numeric
  sub.data <- sub.data %>% arrange(Sample)
  sub.data["Time"] <- (AA_T2.time+1470)/60
  
  spline.data <- no_Oxy.splines[no_Oxy.splines$AA==ind_AA,]
  spline.data["Time"] <- (spline.data$Time+1470)/60
  
  AA_spline.p <- ggplot() +
    # geom_point(data=sub.data, aes(x=Time, y=`O18-label-1`),
    #            color="#009E73", size=3) +
    geom_line(data=spline.data[spline.data$Type=="O18_1",],
              aes(x=Time, y=`Value`),
              color="#009E73", size=1) +
    # geom_point(data=sub.data, aes(x=Time, y=`O18-label-2`),
    #            color="#B45100", size=3) +
    geom_line(data=spline.data[spline.data$Type=="O18_2",],
              aes(x=Time, y=`Value`),
              color="#B45100", size=1) +    
    geom_point(data=sub.data, aes(x=Time, y=`C12 PARENT`),
               color="black", size=3) +
    geom_line(data=spline.data[spline.data$Type=="C12",],
              aes(x=Time, y=`Value`),
              color="black", size=3, alpha=0.4) +
    labs(x="Hours after Labeling", y="Relative Abundance",
         title=unique(sub.data$Name)) +
    theme_bw() +
    theme(axis.text=element_text(size=21,colour="black"),
          # plot.title = element_text(size=24, hjust=0.5, colour="#5E4FA2"),
          plot.title = element_text(size=24, hjust=0.5, colour="black"),          
          # axis.title = element_text(size=22),
          axis.title = element_blank(),                    
          panel.border = element_rect(linewidth=2),
          panel.grid.major = element_line(color = "grey70", linewidth = 0.25),
          panel.grid.minor = element_line(color = "grey70", linewidth = 0.25),
          aspect.ratio = 1,
          legend.position = "none") +
    coord_cartesian(xlim=c(24, 50), ylim=c(0,1)) +
    scale_x_continuous(breaks=seq(20,50,5))
  
  return(AA_spline.p) })


all_spline.p <- c(all_spline.p,
                  lapply(one_Oxy_AA, function(ind_AA){

  sub.data <- MBT_AA_matrix[MBT_AA_matrix$AA == ind_AA,]
  sub.data["Sample"] <- gsub("col009b2_T", "", sub.data$Sample) %>% 
    as.numeric
  sub.data <- sub.data %>% arrange(Sample)
  sub.data["Time"] <- (AA_T2.time+1470)/60

  spline.data <- one_Oxy.splines[one_Oxy.splines$AA==ind_AA,]
  spline.data["Time"] <- (spline.data$Time+1470)/60

  AA_spline.p <- ggplot() +
    # geom_point(data=sub.data, aes(x=Time, y=`O18-label-1`),
    #            color="#009E73", size=3) +
    geom_line(data=spline.data[spline.data$Type=="O18_1",],
              aes(x=Time, y=`Value`),
              color="#009E73", size=1) +
    # geom_point(data=sub.data, aes(x=Time, y=`O18-label-2`),
    #            color="#D55E00", size=3) +
    geom_line(data=spline.data[spline.data$Type=="O18_2",],
              aes(x=Time, y=`Value`),
              color="#D55E00", size=1) +
    # geom_point(data=sub.data, aes(x=Time, y=`O18-label-3`),
    #            color="#0072B2", size=3) +
    geom_line(data=spline.data[spline.data$Type=="O18_3",],
              aes(x=Time, y=`Value`),
              color="#0072B2", size=1) +
    geom_point(data=sub.data, aes(x=Time, y=`C12 PARENT`),
               color="black", size=3) +
    geom_line(data=spline.data[spline.data$Type=="C12",],
              aes(x=Time, y=`Value`),
              color="black", size=3, alpha=0.4) +
    labs(x="Hours after Labeling", y="Relative Abundance",
         title=unique(sub.data$Name)) +
    theme_bw() +
    theme(axis.text=element_text(size=21,colour="black"),
          # plot.title = element_text(size=24, hjust=0.5, colour="#E7298A"),
          plot.title = element_text(size=24, hjust=0.5, colour="black"),          
          # axis.title = element_text(size=22),
          axis.title = element_blank(),                    
          panel.border = element_rect(linewidth=2),
          panel.grid.major = element_line(color = "grey70", linewidth = 0.25),
          panel.grid.minor = element_line(color = "grey70", linewidth = 0.25),
          aspect.ratio = 1,
          legend.position = "none") +
    coord_cartesian(xlim=c(24, 50), ylim=c(0,1)) +
    scale_x_continuous(breaks=seq(20,50,5))

  return(AA_spline.p) }) )


all_spline.p <- c(all_spline.p,
                  lapply(two_Oxy_AA, function(ind_AA){

  sub.data <- MBT_AA_matrix[MBT_AA_matrix$AA == ind_AA,]
  sub.data["Sample"] <- gsub("col009b2_T", "", sub.data$Sample) %>% 
    as.numeric
  sub.data <- sub.data %>% arrange(Sample)
  sub.data["Time"] <- (AA_T2.time+1470)/60

  spline.data <- two_Oxy.splines[two_Oxy.splines$AA==ind_AA,]
  spline.data["Time"] <- (spline.data$Time+1470)/60

  AA_spline.p <- ggplot() +
    # geom_point(data=sub.data, aes(x=Time, y=`O18-label-1`),
    #            color="#009E73", size=3) +
    geom_line(data=spline.data[spline.data$Type=="O18_1",],
              aes(x=Time, y=`Value`),
              color="#009E73", size=1) +
    # geom_point(data=sub.data, aes(x=Time, y=`O18-label-2`),
    #            color="#D55E00", size=3) +
    geom_line(data=spline.data[spline.data$Type=="O18_2",],
              aes(x=Time, y=`Value`),
              color="#D55E00", size=1) +
    # geom_point(data=sub.data, aes(x=Time, y=`O18-label-3`),
    #            color="#0072B2", size=3) +
    geom_line(data=spline.data[spline.data$Type=="O18_3",],
              aes(x=Time, y=`Value`),
              color="#0072B2", size=1) +
    # geom_point(data=sub.data, aes(x=Time, y=`O18-label-4`),
    #            color="#CC79A7", size=3) +
    geom_line(data=spline.data[spline.data$Type=="O18_4",],
              aes(x=Time, y=`Value`),
              color="#CC79A7", size=1) +
    geom_point(data=sub.data, aes(x=Time, y=`C12 PARENT`),
               color="black", size=3) +
    geom_line(data=spline.data[spline.data$Type=="C12",],
              aes(x=Time, y=`Value`),
              color="black", size=3, alpha=0.4) +
    labs(x="Hours after Labeling", y="Relative Abundance",
         title=unique(sub.data$Name)) +
    theme_bw() +
    theme(axis.text=element_text(size=21,colour="black"),
          # plot.title = element_text(size=24, hjust=0.5, colour="#F0E442"),
          plot.title = element_text(size=24, hjust=0.5, colour="black"),          
          # axis.title = element_text(size=22),
          axis.title = element_blank(),          
          panel.border = element_rect(linewidth=2),
          panel.grid.major = element_line(color = "grey70", linewidth = 0.25),
          panel.grid.minor = element_line(color = "grey70", linewidth = 0.25),
          aspect.ratio = 1,
          legend.position = "none") +
    coord_cartesian(xlim=c(24, 50), ylim=c(0,1)) +
    scale_x_continuous(breaks=seq(20,50,5))

  return(AA_spline.p) }) )

names(all_spline.p) <- c(no_Oxy_AA, one_Oxy_AA, two_Oxy_AA)

```



```{r Median plots of AAs }

# #Uncomment for new image!
# tiff("graphs.tiff", units="in",
#      width=9, height=5, res=300)

all_spline.p[["X"]] | all_spline.p[["U"]] | all_spline.p[["Z"]]

# dev.off() #Uncomment for new image!

```


```{r Supp Figure of all amino acids }

# #Uncomment for new image!
# tiff("graph.tiff", units="in",
#      width=14, height=13, res=300)

(all_spline.p[["R"]] | all_spline.p[["G"]] | all_spline.p[["V"]] | all_spline.p[["H"]]) /
  (all_spline.p[["I"]] | all_spline.p[["K"]] | all_spline.p[["M"]] | all_spline.p[["F"]]) /
  (all_spline.p[["P"]] | all_spline.p[["W"]] | all_spline.p[["T"]] | all_spline.p[["Y"]]) /
  (all_spline.p[["S"]] | all_spline.p[["Q"]] | all_spline.p[["D"]] | all_spline.p[["E"]])

# dev.off() #Uncomment for new image!

```


```{r Generating matrix to fit peptide kds }

AA_matrix_fit <- data.frame(Time=seq(0, 2886, by = 1))

AA_matrix_fit <- cbind(AA_matrix_fit,
                       do.call(cbind, lapply(unique(all_splines.merge$AA),
                                             function(AA){
                                               
  sub_data <- all_splines.merge[all_splines.merge$AA==AA&
                                  all_splines.merge$Type=="C12",]
  AA_labels <- unique(sub_data$Labels)

  if (AA %in% no_Oxy_AA) { p_ao <- sub_data$Value^(1/2)  }
  else if (AA %in% one_Oxy_AA) { p_ao <- sub_data$Value^(2/3)  }
  else if (AA %in% two_Oxy_AA) { p_ao <- sub_data$Value^(3/4)  }  
  
  out_col <- data.frame(AA_Name=p_ao)
  colnames(out_col) <- AA
  
  return(out_col) })))

matrix_header <- colnames(AA_matrix_fit)[2:length(colnames(AA_matrix_fit))]
AA_matrix_fit <- AA_matrix_fit %>% as.matrix

head(AA_matrix_fit)

```


```{r Function for filtering MS3 RTS Data }

filter_raw <- function(csv.file) {

  sn.cols <- c("126 Sn", "127n Sn", "127c Sn", "128n Sn", "128c Sn", "129n Sn",
               "129c Sn", "130n Sn", "130c Sn", "131n Sn", "131c Sn", "132n Sn",
               "132c Sn", "133n Sn", "133c Sn", "134n Sn", "134c Sn", "135n Sn")

  #Selecting columns needed for filtering and data analysis
  raw.columns <- c('Protein ID', 'Parsimony', 'Trimmed Peptide', sn.cols,
                   'Theo m/z', 'z', 'Isolation m/z', "Isolation Specificity")

  
  cat("Reading",  tail(unlist(strsplit(csv.file, "/")), n = 1), "...\n\n")  
    
  data.df <- fread(input = csv.file, select = raw.columns) %>%
    as.data.frame
  
  cat("Initial rows:\t\t\t\t\t", nrow(data.df), "\n")

  #'*Parsimony, REV sequences, contaminants, and oxM*
  data.df <- data.df[data.df$Parsimony %in% c("R", "U"),] #Drop NA Parsimony
  data.df <- data.df[!grepl("#", data.df$`Protein ID`),] #Remove reverse sequences
  data.df <- data.df[!grepl('contaminant', data.df$`Protein ID`),] #Remove contaminants
  data.df <- data.df[!grepl("\\*", data.df$`Trimmed Peptide`),] #Remove oxM
  
  cat("After Initial Parsimony/REV/Contam/oxM Filter:\t", nrow(data.df), "\n")

  data.df <- data.df[data.df$z==2 | data.df$z==3, ]

  cat("After Charge State Filter:\t\t\t", nrow(data.df), "\n")  
      
  # data.df <- data.df[data.df$`Isolation Specificity` > 0.75,]

  cat("After Isolation Specificity Filter:\t\t", nrow(data.df), "\n")
  
  #'*M0 Filter*  
  #Calculate theoretical/observed masses + "error"
  # ... Then select rows within error range
  data.df <- data.df[((data.df['z']*data.df['Isolation m/z']) >
                        ((data.df['z']*data.df['Theo m/z']) - 0.1)) &
                       ((data.df['z']*data.df['Isolation m/z']) <
                          ((data.df['z']*data.df['Theo m/z']) + 0.1)), ]
  
  cat("After M0 Filter:\t\t\t\t", nrow(data.df), "\n")  

  #'*Missed Cleavages*
  #Remove peptides with missed cleavages
  # ... Contains KR after removing last AA
  data.df <- data.df[!(grepl("K",
                        str_sub(data.df$`Trimmed Peptide`, end=-2))),]
  data.df <- data.df[!(grepl("R",
                        str_sub(data.df$`Trimmed Peptide`, end=-2))),]
  cat("After removing Missed Cleavages:\t\t", nrow(data.df), "\n")
  
  #'*TMTpro Signal*
  #Signal per channel
  # data.df["Sn_per_channel"] <- apply(data.df, 1, function(x) {
  #   return(all(as.numeric(x[sn.cols]) >= 4)) })
  # data.df <- data.df[data.df$Sn_per_channel==TRUE,]

  #Total signal
  data.df["sum_sn"] <- rowSums(data.df[sn.cols])
  data.df <- data.df[(data.df$z==2 & data.df$sum_sn>257)|
                       (data.df$z==3 & data.df$sum_sn>529),]  
    
  cat("After TMTpro Signal Filter:\t\t\t", nrow(data.df), "\n")  
  
  #Removing unnecessary columns and renaming data
  data.df[c("Parsimony", "Sn_per_channel", "z",
            "Theo m/z", "Isolation m/z", "Isolation Specificity")] <- NULL

  #Summing signal across peptides
  data.df <- data.df %>%
    group_by(`Protein ID`, `Trimmed Peptide`) %>%
    dplyr::summarise(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)),
                     .groups = "drop") %>%
    as.data.frame()  
  
  # #Max signal within peptide group
  # data.df <- data.df %>% group_by(`Trimmed Peptide`) %>%
  #   filter(sum_sn == max(sum_sn)) %>% # ... Select row with max signal
  #   ungroup

  cat("Final Unique Peptides:\t\t\t\t", nrow(data.df), "\n\n\n")

  return(data.df) }
  
# filter_raw("Data/XLA_O18/XLA-O18-T5_RTS-18plex_LongestGFY.csv")

```


```{r Reading raw files and filtering }

#'*MBT Timeseries Replicate 1*
XLA_T9.df <- filter_raw("Data/XLA_O18/XLA-O18-T9_RTS-18plex_Fractionated.csv")
colnames(XLA_T9.df) <- c("Protein_ID", "Peptide",
                         "T0", "O1", "O2", "O3", "O4", "O5", "O6", "O7", "O8", "O9",
                         "O10", "O11", "N2", "N4", "N6", "N8", "N10", "N11", "sum_sn")

#'*MBT Timeseries Replicate 2*
XLA_T10.df <- filter_raw("Data/XLA_O18/XLA-O18-T10_RTS-18plex_Fractionated.csv")
colnames(XLA_T10.df) <- c("Protein_ID", "Peptide",
                          "T0", "O1", "O2", "O3", "O4", "O5", "O6", "O7", "O8", "O9",
                          "O10", "O11", "N2", "N4", "N6", "N8", "N10", "N11", "sum_sn")

```


```{r Fitting exponential decay for AA decay }

#Exponential decay function with two parameters
decay_fcn <- function(t, k1, k2) { k1* exp(-k2*t) }

#Function to fit all peptide decay
peptide_AA_fit <- function(peptide) {
  # Z not used
  # CHLA -> X
  # YN -> U
  mod_pep <- gsub("[CLA]", "X", peptide)
  mod_pep <- gsub("[N]", "U", mod_pep)  
  
  pep_table <- table(strsplit(mod_pep,"")) #Splitting to structure matrix

  #Creating empty matrix of the entire amino acid table
  peptide_matrix <- matrix(0, nrow = nrow(AA_matrix_fit),
                           ncol = ncol(AA_matrix_fit) - 1)  
  colnames(peptide_matrix) <- colnames(AA_matrix_fit)[-1]

  #Replacing AA column with number of amino acids
  for (i in names(pep_table)) { peptide_matrix[,i] <- as.numeric(pep_table[i]) }

  calc_per_AA <- AA_matrix_fit[,-1] ^ peptide_matrix
  pep_deg.tot <- apply(calc_per_AA, 1, prod)
  pep_deg.tot <- pep_deg.tot / pep_deg.tot[1]  

  # Fitting using nlsLM which is less limited for starting values
  #   decay_fcn is an exponential decay function with two parameters defined above
  decay.fit <- nlsLM(pep_deg.tot ~ decay_fcn(seq(0, 2886, by = 1), 1, k2),
                     start = list(k2=0.04),
                     lower = c(0),
                     upper = c(Inf),
                     control = list(maxiter = 1000))
  fit.values <- as.numeric(coef(decay.fit)) #Extracting fit  

  return(data.frame(t(c(1, fit.values)))) }    


#All unique identified peptides
mbt_xla_peps <- unique(c(XLA_T9.df$Peptide, XLA_T10.df$Peptide))

#Applying function to fit each peptide
mbt_xla_pep_fits <- data.frame(Peptide = mbt_xla_peps)

#------------------------------------------------------------

#Setup cluster
cl <- makeCluster(num_cores)

#Export necessary variables/functions to the cluster nodes
clusterExport(cl,
              varlist=c("mbt_xla_peps", "peptide_AA_fit", "decay_fcn",
                        "AA_matrix_fit"))
invisible(clusterEvalQ(cl, library(minpack.lm)))

mbt_xla_pep_fits <- cbind(mbt_xla_pep_fits,
  do.call(rbind, lapply(mbt_xla_peps, peptide_AA_fit)))
colnames(mbt_xla_pep_fits)[2:3] <- c("Pep_k1", "Pep_k2")

stopCluster(cl) #Stop Cluster

#------------------------------------------------------------

head(mbt_xla_pep_fits)

```


```{r Exporting data for normalization / deg rate fit }

filtered_XLA_T9.df <- merge(XLA_T9.df,
                            mbt_xla_pep_fits[c("Peptide", "Pep_k1", "Pep_k2")],
                            by="Peptide") %>%
  arrange(Protein_ID) %>% select(Protein_ID, everything())
filtered_XLA_T10.df <- merge(XLA_T10.df,
                             mbt_xla_pep_fits[c("Peptide", "Pep_k1", "Pep_k2")],
                             by="Peptide") %>%
  arrange(Protein_ID) %>% select(Protein_ID, everything())

write.csv(mbt_xla_pep_fits,
          "Files/Fits/XLA_O18-MBT-TS_Theo-Peptide-Decay.csv",
          row.names = FALSE)
write.csv(filtered_XLA_T9.df,
          "Data/XLA_O18/XLA_O18-T9_Filtered_Data.csv",
          row.names = FALSE)
write.csv(filtered_XLA_T10.df,
          "Data/XLA_O18/XLA_O18-T10_Filtered_Data.csv",
          row.names = FALSE)

```


```{r Plot of Example fits }

min_pep_k2 <- mbt_xla_pep_fits %>%
  filter(min(Pep_k2)==Pep_k2)

max_pep_k2 <- mbt_xla_pep_fits %>%
  filter(max(Pep_k2)==Pep_k2)

med_pep_k2 <- mbt_xla_pep_fits %>%
  mutate(diff = abs(Pep_k2 - median(Pep_k2))) %>%
  filter(diff == min(diff)) %>%
  select(-diff)
med_pep_k2 <- med_pep_k2[1,]

example_fits <- rbind(min_pep_k2, med_pep_k2, max_pep_k2)
example_fits["Type"] <- c("Min", "Median", "Max")

ex.fit_data <- lapply(example_fits$Peptide, function(peptide) {
  
  ex.fit <- example_fits[example_fits$Peptide==peptide,]

  curve_values <- decay_fcn(seq(0,2886,1), ex.fit$Pep_k1, ex.fit$Pep_k2)  

  example.df <- data.frame(Time=seq(0,2886,1)/60,
                           Fit_values=curve_values,
                           Type=rep(ex.fit$Type, length(curve_values)))
  
  return(example.df) })

ex.fit_data <- do.call(rbind, ex.fit_data) 

ex.p <- ggplot() +
  geom_line(data=ex.fit_data[ex.fit_data$Type=="Median",], 
             aes(x=Time, y=Fit_values), color="#009E73", size=1.5) +
  geom_line(data=ex.fit_data[ex.fit_data$Type=="Min",], 
             aes(x=Time, y=Fit_values), color="#CC79A7", size=1.5) +
  
  theme_bw() +
  labs(x="Hours after Labeling", y="Probability of light peptide") +
  theme_bw() +
  theme(axis.text=element_text(size=21,colour="black"),
        plot.title = element_text(size=24, hjust=0.5),
        axis.title = element_text(size=22),
        panel.border = element_rect(linewidth=2),
        panel.grid.major = element_line(color = "grey70", linewidth = 0.25),
        panel.grid.minor = element_line(color = "grey70", linewidth = 0.25),
        aspect.ratio = 1,
        legend.position = "none") +
  coord_cartesian(ylim=c(0,1), xlim=c(0,6))

```


```{r T1/2 for examples }

round(log(2)/example_fits$Pep_k2,0)

```


```{r Example fits plots }

# #Uncomment for new image!
# tiff("Graphs/Frog_AA_Incorporation/XLA_T2_Example_Fits.tiff", units="in",
#      width=4.5, height=4.5, res=300)

ex.p

# dev.off() #Uncomment for new image!

```


```{r Which peptides for paper example }

example_fits

```


```{r Plots of example fits }

#Function to fit all peptide decay
peptide_AA_fit <- function(peptide) {
  # Z not used
  # CHLA -> X
  # YN -> U
  mod_pep <- gsub("[CLA]", "X", peptide)
  mod_pep <- gsub("[N]", "U", mod_pep)  
  
  pep_table <- table(strsplit(mod_pep,"")) #Splitting to structure matrix

  #Creating empty matrix of the entire amino acid table
  peptide_matrix <- matrix(0, nrow = nrow(AA_matrix_fit),
                           ncol = ncol(AA_matrix_fit) - 1)  
  colnames(peptide_matrix) <- colnames(AA_matrix_fit)[-1]

  #Replacing AA column with number of amino acids
  for (i in names(pep_table)) { peptide_matrix[,i] <- as.numeric(pep_table[i]) }

  calc_per_AA <- AA_matrix_fit[,-1] ^ peptide_matrix
  pep_deg.tot <- apply(calc_per_AA, 1, prod)
  pep_deg.tot <- pep_deg.tot / pep_deg.tot[1]  

  # # Fitting using nlsLM which is less limited for starting values
  # #   decay_fcn is an exponential decay function with two parameters defined above
  # decay.fit <- nlsLM(pep_deg.tot ~ decay_fcn(seq(0, 2886, by = 1), 1, k2),
  #                    start = list(k2=0.04),
  #                    lower = c(0),
  #                    upper = c(Inf),
  #                    control = list(maxiter = 1000))
  # fit.values <- as.numeric(coef(decay.fit)) #Extracting fit  

  # plot(seq(0, 2886, by = 1)/60, pep_deg.tot,
  #      xlim=c(0,8), ylim=c(0,1), pch=16)
  # lines(seq(0,8*60,1)/60, decay_fcn(seq(0,8*60,1), 1, fit.values[1]),
  #       col="red")

  return(pep_deg.tot) }

median_pep_residues <- data.frame(Time = seq(0, 2886, by = 1)/60,
                                  Fit_values = peptide_AA_fit("LQLFSTQDGR"))
longest_pep_residues <- data.frame(Time = seq(0, 2886, by = 1)/60,
                                   Fit_values = peptide_AA_fit("HPYWPHK"))

res.p <- ggplot() +
  geom_point(data=longest_pep_residues, 
             aes(x=Time, y=Fit_values), color="#0072B2", size=2,
             shape=1) +
  geom_point(data=median_pep_residues, 
             aes(x=Time, y=Fit_values), color="#E7298A", size=2,
             shape=1) +

  theme_bw() +
  labs(x="Hours after Labeling", y="Probability of light peptide") +
  theme_bw() +
  theme(axis.text=element_text(size=21,colour="black"),
        plot.title = element_text(size=24, hjust=0.5),
        axis.title = element_text(size=22),
        panel.border = element_rect(linewidth=2),
        panel.grid.major = element_line(color = "grey70", linewidth = 0.25),
        panel.grid.minor = element_line(color = "grey70", linewidth = 0.25),
        aspect.ratio = 1,
        legend.position = "none") +
  coord_cartesian(ylim=c(0,1), xlim=c(0,6))

write.csv(median_pep_residues, "Files/Fits/AA_examples/Median_Gast_residue-prob.csv",
          row.names = FALSE)

# #Uncomment for new image!
# tiff("Graphs/Frog_AA_Incorporation/XLA_T2_Example_Fits.tiff", units="in",
#      width=4, height=4, res=300)

res.p

# dev.off() #Uncomment for new image!

```


```{r}

sessionInfo()

```
























